param(
  [Parameter(Mandatory=$true)][string]$DecisionEnvelope,
  [Parameter(Mandatory=$true)][string]$HumanDecision,
  [Parameter(Mandatory=$true)][string]$EvidenceRoot
)
$ErrorActionPreference="Stop"
$PSNativeCommandUseErrorActionPreference=$true
if($PSVersionTable.PSVersion.Major -lt 7){throw "POWERSHELL_7_REQUIRED"}
$Root=(Resolve-Path (Split-Path -Parent $PSScriptRoot)).Path
$DecisionEnvelope=[IO.Path]::GetFullPath($DecisionEnvelope);$EvidenceRoot=[IO.Path]::GetFullPath($EvidenceRoot)
$ExactDecision="APPROVE HAIOS_DESKTOP_CONTROL_PLANE_R1_M12_B5_CANARY_STABILITY_ACTIVATION"
$M11FinalTerminal="HAIOS_DESKTOP_CONTROL_PLANE_R1_M11_ACTIVE_CANARY_QUALIFIED"
$M11FinalCertification="C:\Workspace\haios-desktop-control-m11\evidence\m11\final\m11-final-certification.json"
$M11CertifiedHead="1c32ba789ce89872b36bfed5f7a527b917072d6b"
$M11CertifiedManifest="ad2086df0f8bf6993fbe3756084d826d07b2f58b632d6ab49c1491210640815a"
$CanaryRoot="C:\Workspace\haios-operator-canary";$ExpectedCanaryBranch="main"
$M11RuntimeRoot="C:\Workspace\haios-desktop-control-m11-runtime"
$DeploymentRoot="C:\Workspace\haios-desktop-control-m12-runtime"
$StateRoot=[IO.Path]::GetFullPath((Join-Path $env:LOCALAPPDATA "HAIOS\M12"))
$M10ApiKeyFile=[IO.Path]::GetFullPath((Join-Path $env:LOCALAPPDATA "HAIOS\M10\operator-api-key"))
$M11Task="HAIOS-M11-Operator-Active-Canary";$M12Task="HAIOS-M12-Operator-B5-Canary-Stability"
$DedicatedTunnel="haios-operator-dedicated-tunnel-client";$SharedTunnel="haios-tunnel-client";$ExpectedTunnelRoute="host.docker.internal:8769/mcp";$SecurePort=8768
$RollbackScript=Join-Path $Root "scripts\rollback-m12-b5-to-m11.ps1";$mutationStarted=$false
function Get-Sha256([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()}
function Write-JsonNoBom([string]$Path,$Object){[IO.File]::WriteAllText($Path,(($Object|ConvertTo-Json -Depth 16)+"`n"),[Text.UTF8Encoding]::new($false))}
function Get-ManifestDigest([string]$RepoRoot){$paths=[string[]]@(& git.exe -C $RepoRoot ls-files);if($LASTEXITCODE -ne 0){throw "M12_MANIFEST_ENUM_FAILED"};[Array]::Sort($paths,[StringComparer]::Ordinal);$lines=foreach($rel in $paths){"$(Get-Sha256 (Join-Path $RepoRoot $rel))  $($rel.Replace('\','/'))"};$bytes=[Text.Encoding]::UTF8.GetBytes((($lines -join "`n")+"`n"));[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes)).ToLowerInvariant()}
function Get-ListenerIdentity([int]$PortNumber){@((Get-NetTCPConnection -State Listen -LocalPort $PortNumber -ErrorAction SilentlyContinue|Sort-Object LocalAddress,OwningProcess|ForEach-Object{"$($_.LocalAddress)|$($_.LocalPort)|$($_.OwningProcess)"}))}
function Get-ContainerDigest([string]$Name){$raw=& docker.exe inspect $Name 2>$null;if($LASTEXITCODE -ne 0 -or -not $raw){throw "M12_CONTAINER_UNAVAILABLE:$Name"};$o=($raw|ConvertFrom-Json)[0];$net=@($o.NetworkSettings.Networks.PSObject.Properties|Sort-Object Name|ForEach-Object{[ordered]@{name=$_.Name;network_id=$_.Value.NetworkID;endpoint_id=$_.Value.EndpointID;ip=$_.Value.IPAddress;gateway=$_.Value.Gateway}});$mount=@($o.Mounts|Sort-Object Destination,Type|ForEach-Object{[ordered]@{type=$_.Type;destination=$_.Destination;mode=$_.Mode;rw=$_.RW;propagation=$_.Propagation}});$snap=[ordered]@{id=$o.Id;created=$o.Created;image_id=$o.Image;config_image=$o.Config.Image;path=$o.Path;args=@($o.Args);network_mode=$o.HostConfig.NetworkMode;restart_policy=$o.HostConfig.RestartPolicy;mounts=$mount;networks=$net};$bytes=[Text.Encoding]::UTF8.GetBytes(($snap|ConvertTo-Json -Depth 8 -Compress));[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes)).ToLowerInvariant()}
function Write-Journal([string]$Event,$Data=$null){$r=[ordered]@{utc=[DateTime]::UtcNow.ToString('o');event=$Event};if($null -ne $Data){$r.data=$Data};[IO.File]::AppendAllText($JournalPath,(($r|ConvertTo-Json -Depth 12 -Compress)+"`n"),[Text.UTF8Encoding]::new($false))}
function AuthorityFail([string]$Why){throw "M12_ACTIVATION_AUTHORITY_CURRENTNESS_FAILED:$Why"}
if(-not(Test-Path -LiteralPath $DecisionEnvelope)){AuthorityFail "DECISION_ENVELOPE_MISSING"}
$Envelope=Get-Content -Raw -LiteralPath $DecisionEnvelope|ConvertFrom-Json
if([string]$Envelope.required_human_decision -ne $ExactDecision -or $HumanDecision -ne $ExactDecision){AuthorityFail "HUMAN_DECISION_MISMATCH"}
if([string]$Envelope.m11_final_terminal -ne $M11FinalTerminal){AuthorityFail "M11_FINAL_TERMINAL_MISMATCH"}
if([IO.Path]::GetFullPath([string]$Envelope.m11_final_cert_path) -ne $M11FinalCertification){AuthorityFail "M11_FINAL_CERT_PATH_MISMATCH"}
if([string]$Envelope.m11_certified_head -ne $M11CertifiedHead -or [string]$Envelope.m11_certified_manifest_sha256 -ne $M11CertifiedManifest){AuthorityFail "M11_CERTIFIED_IDENTITY_MISMATCH"}
if([string]$Envelope.canary_root -ne $CanaryRoot -or [string]$Envelope.canary_branch -ne $ExpectedCanaryBranch){AuthorityFail "CANARY_IDENTITY_MISMATCH"}
if([string]$Envelope.m11_task_name -ne $M11Task -or [string]$Envelope.m12_task_name -ne $M12Task){AuthorityFail "TASK_IDENTITY_MISMATCH"}
foreach($field in @("tunnel_mutation_authorized","m10_api_key_rotation_authorized","s2_authorized","destructive_authorized","generic_exec_authorized","generic_shell_authorized")){$property=$Envelope.PSObject.Properties[$field];if($null -eq $property -or $property.Value -isnot [bool] -or $property.Value -ne $false){AuthorityFail "FORBIDDEN_AUTHORITY_FIELD_INVALID:$field"}}
if(-not(Test-Path -LiteralPath $M11FinalCertification)){AuthorityFail "M11_FINAL_CERT_MISSING"}
if((Get-Sha256 $M11FinalCertification) -ne [string]$Envelope.m11_final_cert_sha256){AuthorityFail "M11_FINAL_CERT_DRIFT"}
$cert=Get-Content -Raw -LiteralPath $M11FinalCertification|ConvertFrom-Json
if([string]$cert.terminal -ne $M11FinalTerminal -or [string]$cert.candidate_head -ne $M11CertifiedHead -or [string]$cert.candidate_manifest_sha256 -ne $M11CertifiedManifest){AuthorityFail "M11_FINAL_CERT_NOT_CURRENT"}
if((Get-Sha256 $PSCommandPath) -ne [string]$Envelope.executor_sha256){AuthorityFail "EXECUTOR_HASH_DRIFT"}
if((Get-Sha256 $RollbackScript) -ne [string]$Envelope.rollback_sha256){AuthorityFail "ROLLBACK_HASH_DRIFT"}
New-Item -ItemType Directory -Force -Path $EvidenceRoot|Out-Null;$JournalPath=Join-Path $EvidenceRoot "m12-execution-journal.jsonl"
$candidateHead=(& git.exe -C $Root rev-parse HEAD).Trim();if($LASTEXITCODE -ne 0 -or $candidateHead -ne [string]$Envelope.candidate_head){AuthorityFail "CANDIDATE_HEAD_DRIFT"}
if((& git.exe -C $Root status --porcelain).Length -ne 0){AuthorityFail "CANDIDATE_WORKTREE_DIRTY"};if((Get-ManifestDigest $Root) -ne [string]$Envelope.candidate_manifest_sha256){AuthorityFail "CANDIDATE_MANIFEST_DRIFT"}
if(-not(Test-Path -LiteralPath $M11RuntimeRoot)){AuthorityFail "M11_RUNTIME_MISSING"};$m11RuntimeHead=(& git.exe -C $M11RuntimeRoot rev-parse HEAD).Trim();if($LASTEXITCODE -ne 0 -or $m11RuntimeHead -ne $M11CertifiedHead -or $m11RuntimeHead -ne [string]$Envelope.m11_runtime_head){AuthorityFail "M11_RUNTIME_HEAD_DRIFT"}
if((& git.exe -C $M11RuntimeRoot status --porcelain).Length -ne 0){AuthorityFail "M11_RUNTIME_DIRTY"};if((Get-ManifestDigest $M11RuntimeRoot) -ne $M11CertifiedManifest -or (Get-ManifestDigest $M11RuntimeRoot) -ne [string]$Envelope.m11_runtime_manifest_sha256){AuthorityFail "M11_RUNTIME_MANIFEST_DRIFT"}
$canaryBranch=(& git.exe -C $CanaryRoot branch --show-current).Trim();$canaryHead=(& git.exe -C $CanaryRoot rev-parse HEAD).Trim();if($LASTEXITCODE -ne 0 -or $canaryBranch -ne $ExpectedCanaryBranch -or $canaryHead -ne [string]$Envelope.canary_head -or (& git.exe -C $CanaryRoot status --porcelain).Length -ne 0){AuthorityFail "CANARY_PREIMAGE_DRIFT"}
if(-not(Test-Path -LiteralPath $M10ApiKeyFile) -or (Get-Sha256 $M10ApiKeyFile) -ne [string]$Envelope.m10_api_key_sha256){AuthorityFail "M10_API_KEY_DRIFT"}
$m11TaskObject=Get-ScheduledTask -TaskName $M11Task -ErrorAction SilentlyContinue;if(-not $m11TaskObject -or [string]$m11TaskObject.State -ne 'Running'){AuthorityFail "M11_TASK_NOT_RUNNING"};$m11Action=@($m11TaskObject.Actions)[0];if([string]$m11Action.Execute -ne [string]$Envelope.m11_task_execute -or [string]$m11Action.Arguments -ne [string]$Envelope.m11_task_arguments){AuthorityFail "M11_TASK_ACTION_DRIFT"};if(-not([string]$m11Action.Arguments).Contains("run-m11-active-canary-supervisor.mjs")){AuthorityFail "M11_TASK_IDENTITY_DRIFT"}
if(Get-ScheduledTask -TaskName $M12Task -ErrorAction SilentlyContinue){AuthorityFail "M12_TASK_COLLISION"};if(Test-Path -LiteralPath $DeploymentRoot){AuthorityFail "M12_DEPLOYMENT_COLLISION"};if(Test-Path -LiteralPath $StateRoot){AuthorityFail "M12_STATE_COLLISION"}
$m11Probe=Join-Path $M11RuntimeRoot "scripts\probe-m11-active-canary-host.mjs";$m11Proof=Join-Path $EvidenceRoot "m11-active-authority-proof.json";& "C:\Program Files\nodejs\node.exe" $m11Probe $M10ApiKeyFile $m11Proof *> $null;if($LASTEXITCODE -ne 0 -or -not(Test-Path -LiteralPath $m11Proof)){AuthorityFail "M11_RUNTIME_PREIMAGE_INVALID"}
$listener8768=@(Get-ListenerIdentity $SecurePort);$listener8769=@(Get-ListenerIdentity 8769);if(($listener8768 -join ',') -ne (@($Envelope.listener_8768)-join ',')){AuthorityFail "SECURE_8768_DRIFT"};if(($listener8769 -join ',') -ne (@($Envelope.listener_8769)-join ',')){AuthorityFail "OPERATOR_8769_DRIFT"}
if((Get-ContainerDigest $DedicatedTunnel) -ne [string]$Envelope.dedicated_tunnel_sha256 -or (Get-ContainerDigest $SharedTunnel) -ne [string]$Envelope.shared_tunnel_sha256){AuthorityFail "TUNNEL_DIGEST_DRIFT"};$dedicated=(& docker.exe inspect $DedicatedTunnel|ConvertFrom-Json)[0];if(-not((@($dedicated.Args)-join ' ').Contains($ExpectedTunnelRoute))){AuthorityFail "DEDICATED_ROUTE_DRIFT"}
Write-Journal "M12_HUMAN_AUTHORITY_ACCEPTED" @{decision_matched=$true}
Write-Journal "M12_M11_FINAL_CERT_CURRENT" @{sha256=[string]$Envelope.m11_final_cert_sha256}
Write-Journal "M12_CANDIDATE_CURRENT" @{candidate_manifest_sha256=[string]$Envelope.candidate_manifest_sha256}
Write-Journal "M12_M11_TASK_PREIMAGE_CURRENT" @{execute=[string]$Envelope.m11_task_execute;arguments=[string]$Envelope.m11_task_arguments}
Write-Journal "M12_CANARY_PREIMAGE_CURRENT" @{canary_branch=$canaryBranch;canary_head=$canaryHead}
Write-Journal "M12_M10_API_KEY_CURRENT" @{m10_api_key_sha256=[string]$Envelope.m10_api_key_sha256}
Write-Journal "M12_TUNNEL_PREIMAGE_CURRENT" @{route=$ExpectedTunnelRoute}
Write-Journal "M12_LISTENERS_PREIMAGE_CURRENT" @{listener_8768=$listener8768;listener_8769=$listener8769}
Write-Journal "M12_EXECUTOR_CURRENT" @{sha256=[string]$Envelope.executor_sha256}
Write-Journal "M12_ROLLBACK_CURRENT" @{sha256=[string]$Envelope.rollback_sha256}
function Set-M12StateAcl([string]$Path){$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$security=[Security.AccessControl.DirectorySecurity]::new();$security.SetAccessRuleProtection($true,$false);$inherit=[Security.AccessControl.InheritanceFlags]"ContainerInherit,ObjectInherit";$prop=[Security.AccessControl.PropagationFlags]::None;$allow=[Security.AccessControl.AccessControlType]::Allow;$systemSid=[Security.Principal.SecurityIdentifier]::new([Security.Principal.WellKnownSidType]::LocalSystemSid,$null);$adminsSid=[Security.Principal.SecurityIdentifier]::new([Security.Principal.WellKnownSidType]::BuiltinAdministratorsSid,$null);foreach($sid in @($identity.User,$systemSid,$adminsSid)){$rule=[Security.AccessControl.FileSystemAccessRule]::new($sid,[Security.AccessControl.FileSystemRights]::FullControl,$inherit,$prop,$allow);$security.AddAccessRule($rule)|Out-Null};Set-Acl -LiteralPath $Path -AclObject $security}
try{
  Write-Journal "M12_MUTATION_BEGIN";$mutationStarted=$true
  & git.exe -C $Root worktree add --detach $DeploymentRoot ([string]$Envelope.candidate_head);if($LASTEXITCODE -ne 0){throw "M12_DEPLOYMENT_WORKTREE_CREATE_FAILED"};if((Get-ManifestDigest $DeploymentRoot) -ne [string]$Envelope.candidate_manifest_sha256){throw "M12_DEPLOYMENT_MANIFEST_DRIFT"}
  Push-Location $DeploymentRoot;try{& npm.cmd ci --offline --ignore-scripts --no-audit --no-fund;if($LASTEXITCODE -ne 0){throw "M12_DEPLOYMENT_NPM_CI_FAILED"};& npm.cmd run build;if($LASTEXITCODE -ne 0){throw "M12_DEPLOYMENT_BUILD_FAILED"}}finally{Pop-Location};Write-Journal "M12_DEPLOYMENT_READY"
  New-Item -ItemType Directory -Path $StateRoot|Out-Null;Set-M12StateAcl $StateRoot;$Worktrees=Join-Path $StateRoot "worktrees";New-Item -ItemType Directory -Path $Worktrees|Out-Null;$ConfigPath=Join-Path $StateRoot "host-config.json";$Config=[ordered]@{apiKeyFile=$M10ApiKeyFile;worktreeRoot=$Worktrees;stateRoot=$StateRoot;allowedProjects=[ordered]@{"operator-canary"=$CanaryRoot};port=8769;mode="ACTIVE";activationScope="M12_B5_CANARY_STABILITY_ONLY"};Write-JsonNoBom $ConfigPath $Config;if((Get-Sha256 $M10ApiKeyFile) -ne [string]$Envelope.m10_api_key_sha256){throw "M12_M10_API_KEY_POSTCONFIG_DRIFT"};Write-Journal "M12_STATE_READY"
  Stop-ScheduledTask -TaskName $M11Task;$deadline=[DateTime]::UtcNow.AddSeconds(30);while((Get-NetTCPConnection -State Listen -LocalPort 8769 -ErrorAction SilentlyContinue) -and [DateTime]::UtcNow -lt $deadline){Start-Sleep -Milliseconds 500};if(Get-NetTCPConnection -State Listen -LocalPort 8769 -ErrorAction SilentlyContinue){throw "M12_PORT_8769_NOT_RELEASED"};Write-Journal "M12_M11_RUNTIME_STOPPED"
  $identityName=[Security.Principal.WindowsIdentity]::GetCurrent().Name;$node="C:\Program Files\nodejs\node.exe";$supervisor=Join-Path $DeploymentRoot "scripts\run-m12-active-canary-supervisor.mjs";$action=New-ScheduledTaskAction -Execute $node -Argument "`"$supervisor`" `"$ConfigPath`"";$trigger=New-ScheduledTaskTrigger -AtLogOn -User $identityName;$principal=New-ScheduledTaskPrincipal -UserId $identityName -LogonType Interactive -RunLevel Limited;$settings=New-ScheduledTaskSettingsSet -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1);$task=New-ScheduledTask -Action $action -Trigger $trigger -Principal $principal -Settings $settings;Register-ScheduledTask -TaskName $M12Task -InputObject $task|Out-Null;Start-ScheduledTask -TaskName $M12Task;Write-Journal "M12_ACTIVE_TASK_STARTED"
  $probe=Join-Path $DeploymentRoot "scripts\probe-m12-b5-host.mjs";$activeProof=Join-Path $EvidenceRoot "m12-active-host-proof.json";$deadline=[DateTime]::UtcNow.AddSeconds(45);$activeReady=$false
  do{Start-Sleep -Milliseconds 500;$oldNativeErrorPreference=$PSNativeCommandUseErrorActionPreference;$PSNativeCommandUseErrorActionPreference=$false;try{& $node $probe $M10ApiKeyFile $activeProof *> $null;$probeExit=$LASTEXITCODE}finally{$PSNativeCommandUseErrorActionPreference=$oldNativeErrorPreference};if($probeExit -eq 0 -and (Test-Path -LiteralPath $activeProof)){$activeReady=$true;break}}while([DateTime]::UtcNow -lt $deadline)
  if(-not $activeReady){throw "M12_ACTIVE_HOST_MCP_PROOF_FAILED"};Write-Journal "M12_ACTIVE_HOST_READY"
  if((Get-ContainerDigest $DedicatedTunnel) -ne [string]$Envelope.dedicated_tunnel_sha256 -or (Get-ContainerDigest $SharedTunnel) -ne [string]$Envelope.shared_tunnel_sha256){throw "M12_TUNNEL_POSTIMAGE_DRIFT"};if((@(Get-ListenerIdentity $SecurePort)-join ',') -ne (@($Envelope.listener_8768)-join ',')){throw "M12_SECURE_8768_POSTIMAGE_DRIFT"};Write-Journal "M12_TUNNEL_POSTIMAGE_CURRENT"
  $result=[ordered]@{candidate_head=[string]$Envelope.candidate_head;mode="ACTIVE";activation_scope="M12_B5_CANARY_STABILITY_ONLY";canary_root=$CanaryRoot;canary_branch=$canaryBranch;canary_head_preimage=[string]$Envelope.canary_head;m10_api_key_rotated=$false;tunnel_route_changed=$false;shared_8768_changed=$false};Write-JsonNoBom (Join-Path $EvidenceRoot "m12-activation-result.json") $result;Write-Journal "M12_FORWARD_ACTIVATION_COMPLETE";Write-Host "M12_B5_CANARY_STABILITY_ACTIVATION_FORWARD_COMPLETE"
}catch{$forwardError=$_.Exception.Message;Write-Journal "M12_FORWARD_FAILURE" @{error=$forwardError};if($mutationStarted){try{& pwsh -NoProfile -File $RollbackScript -DecisionEnvelope $DecisionEnvelope -ExecutionJournal $JournalPath -EvidenceRoot $EvidenceRoot;if($LASTEXITCODE -ne 0){throw "M12_ROLLBACK_EXIT_$LASTEXITCODE"};Write-Journal "M12_AUTOMATIC_ROLLBACK_COMPLETE"}catch{Write-Journal "M12_AUTOMATIC_ROLLBACK_BLOCKED" @{error=$_.Exception.Message};throw "M12_FORWARD_FAILED_ROLLBACK_BLOCKED:$forwardError"}};throw "M12_FORWARD_FAILED_ROLLED_BACK:$forwardError"}